### ISSUE TITLE
hook cmd arguments not being customized

### ISSUE THREAD

**Issue by puphubv** [breard-r/acmed#157]
It seems I've missed something simple...

I've defined a hook:

[[hook]]
name = "dns-01-hook-myauth"
type = ["challenge-dns-01"]
cmd = "auth.sh"
args = [ "{ identifier }", "{ proof }" ]

It's literally being run as:

auth.sh "{ identifier }" "{ proof }" 

instead of:

auth.sh example.com Kdi3k28dksld8...

**Comment by breard-r** [comment]
You need to write two curly brackets:

```
 args = [ "{{ identifier }}", "{{ proof }}" ]
```

For more information, you can refer to the [MiniJinja syntax](https://docs.rs/minijinja/latest/minijinja/syntax/index.html).

I was wondering what could have lead you to put single curly brackets and found out there is one example in the manual that contains this error. I'm fixing this right now.

**Comment by puphubv** [comment]
Oops...  I was reading an old version of the manpage from:

https://cdn.homespan.com/cgi-bin/man.cgi?section=5&topic=ACMED

Thanks

**Comment by breard-r** [comment]
I see. The template engine changed [a year ago](https://github.com/breard-r/acmed/blob/main/CHANGELOG.md#0220---2023-12-20), so as you mentioned there may still be outdated documentation in the wild using the previous syntax.
