### ISSUE TITLE
PID file + foreground

### ISSUE THREAD

**Issue by dbrgn** [breard-r/acmed#25]
It seems that when running acmed in foreground using `--foreground`, a PID file is still created. is this required?

(Furthermore, it appears that the PID file is not cleaned up when the process stops with an error on parsing the config file...)

**Comment by breard-r** [comment]
> is this required?

No it's not. However, it is required that when running in the foreground you have the possibility to specify a PID file (see #7). It shouldn't be too hard to fix it, I'll do it quite soon.

**Comment by dbrgn** [comment]
Thanks!

**Comment by breard-r** [comment]
Well, thank you for reporting it ! :)
