### ISSUE TITLE
README clarification on key sizes

### ISSUE THREAD

**Issue by polarathene** [breard-r/acmed#34]
The README [why-is-rsa-2048-the-default section](https://github.com/breard-r/acmed#why-is-rsa-2048-the-default) makes two statements that could benefit a user a bit more to clarify.

> *It is not obvious at the first sight, but RSA 4096 is NOT twice more secure than RSA 2048. In fact, it adds a lot more calculation while providing only a small security improvement.*

Appears to be related to the term [security level](https://en.wikipedia.org/wiki/Security_level)? I came across an article that explained it a bit more clearly [here](https://www.ssl.com/article/comparing-ecdsa-vs-rsa/):

> In this regard, a common RSA 2048-bit public key provides a security level of 112 bits. However, ECDSA requires only 224-bit sized public keys to provide the same 112-bit security level.

> In the next common level of 128 bits, RSA requires a 3072-bit key, while ECDSA only 256 bits.

A similar comparison of *security level* without comparing to ECDSA is [presented on Wikipedia](https://en.wikipedia.org/wiki/Key_size):

> 1024-bit RSA keys are equivalent in strength to 80-bit symmetric keys, 2048-bit RSA keys to 112-bit symmetric keys, 3072-bit RSA keys to 128-bit symmetric keys, and 15360-bit RSA keys to 256-bit symmetric keys.

This isn't an area I understand that well, but I thought increasing the bits still has a notable impact on computational costs? (to attack)

2(1-bit), 4, 8, 16 ,32, 64 (8 bits), the amount of values doubles with each additional bit added. The above information doesn't clarify symmetric key size equivalent bits (which I've referred to as *security level* above, but is what these bit values are meant to be representing?), but we can see that between 2048 and 3072 RSA sizes, 16 bits should be well over 2x the amount of computation to break? 

[This StackExchange answer](https://crypto.stackexchange.com/questions/8687/security-strength-of-rsa-in-relation-with-the-modulus-size) shows RSA-4096 should be ~150 bits, with a delta of ~40 bits. [This article](https://xtendo.org/bit_security_level) seems to address the topic well in regards to understanding the statement the README has(although I don't quite know if the 2x strength you mention implying it's less of an increase is valid?). Perhaps both, or one of these links would be suitable to add to the README?

---

> *If so, using RSA 4096 in the final certificate will not add any additional security since a system's global security level is equal to the level of its weakest point.*

This also had me curious, and I'm not sure if it's entirely valid either? See [this StackExchange discussion](https://security.stackexchange.com/questions/2558/should-the-bit-strength-selection-of-a-child-certificate-be-influenced-by-the-ca).

I think you're referring to security here in terms of CA certs in the chain, but not the end-entity cert strength which is still useful for encryption security of messages being exchanged, whereas the other certs are for validation, but breaking them won't decrypt any prior recorded encrypted messages. 

The link seems to indicate that there is still benefit (security wise) for end-entity certs that have larger key sizes(possibly not for DHE though where it's only used for signing but not in the key exchange according to one of the comments there).

**Comment by breard-r** [comment]
> Appears to be related to the term security level
> <https://en.wikipedia.org/wiki/Security_level>? I came across an article
> that explained it a bit more clearly here
> <https://www.ssl.com/article/comparing-ecdsa-vs-rsa/>:

> This isn't an area I understand that well, but I thought increasing the
> bits still has a notable impact on computational costs? (to attack)

To understand both the text in the README and the estimated security
level, you have to understand how RSA works. The core of this algorithm
is based on prime number: the private key contains 2 primes number and
the public key is the multiplication of those two primes (hence a
semiprime number). Yes, there is also other stuff in both the private
and public keys, but that's out of scope here.

The number of bits indicated in the RSA name is the number of bits of
the public semiprime. When constructing an RSA key pair, you may chose
any prime number, but a very common strategy is to chose 2 primes of the
same size, generally half the size of the semiprime. Therefore, RSA-2048
has a private key with 2 prime numbers of 1024 bits each and a public
key with a 2048 bits semiprime. And obviously, RSA-4096 has 2 private
prime numbers of 2048 bits and a public semiprime of 4096 bits. Yes,
it's possible to have prime numbers of different sizes, but that's out
of the subject and it brings it's own security problems. Just so you
know, it's also possible to have more than 2 secret prime numbers, but
that's also out of the subject.

Because of how RSA work and is implemented, we can clearly see that one
of the security aspect is not the number of bits of the public
semiprime, but the number of prime numbers with the size of half this
number of bits. On a graphic if, for each number of bits, you calculate
the number of prime numbers of this size and then trace a curve based of
those points, you will see that it looks like a logarithmic curve.
Hence, even if the number of prime numbers always grows with the number
of bits, the further you go the lower it grows by. That's why doubling
the RSA semiprime size will increase the security (there is more prime
number to chose from) but not in a significant way since that at this
point it doesn't grows a lot. However, since the size of prime numbers
doubled, the calculation time (for legitimate operations) growth a lot.

This is why you won't see RSA size higher than 4096 even if it's
possible: choosing bigger RSA size has a rather small beneficial impact
on security but a huge drawback in (legitimate) computational cost. At
some point it's just of no use to go further and many people think this
point is a 4096 bits semiprime.

Before math and experts shred me into pieces for oversimplification this
explanation, I would say that it is not an academical course on RSA. I
am well aware of all the things I did not spoke about, I simply wanted
the concept to be understood in a message of less than 42 pages.


> This also had me curious, and I'm not sure if it's entirely valid
> either? See this StackExchange discussion
> <https://security.stackexchange.com/questions/2558/should-the-bit-strength-selection-of-a-child-certificate-be-influenced-by-the-ca>.
> 
> I think you're referring to security here in terms of CA certs in the
> chain, but not the end-entity cert strength which is still useful for
> encryption security of messages being exchanged, whereas the other certs
> are for validation, but breaking them won't decrypt any prior recorded
> encrypted messages.
> 
> The link seems to indicate that there is still benefit (security wise)
> for end-entity certs that have larger key sizes(possibly not for DHE
> though where it's only used for signing but not in the key exchange
> according to one of the comments there).


In TLS, nowedays, the RSA keypair has absolutely no impact on data
encryption. It is exclusively used only for authentication. Therefore
no, you don't have any benefit in using a bigger RSA key than the lowest
in the chain.

In some cases, which the reply in the stackexchange tread refers to, the
RSA key was used to encrypt the symmetric key pair during the key
exchange. This way to exchange the symmetric key is obsolete and should
be disabled since it does not provides any forward secrecy: if the
private key leaks, every previous communication that has been recorded
can now be decrypted. Modern key exchanges uses a Diffie-Hellman key
exchange with ephemeral parameters (DHE or the ECDHE).

Conclusion: check the date before believing something you see on the
internet, the stackexchange thread dates back in 2011. In 9 years things
evolved and what was true at that time is mostly false today (at least
about this subject).

**Comment by polarathene** [comment]
Thanks for taking the time to respond. I had put together a slightly better response but lost it when my browser crashed just as I was about to send :(

> *On a graphic if, for each number of bits, you calculate the number of prime numbers of this size and then trace a curve based of those points, you will see that it looks like a logarithmic curve. Hence, even if the number of prime numbers always grows with the number of bits, the further you go the lower it grows by.*

> *choosing bigger RSA size has a rather small beneficial impact on security but a huge drawback in (legitimate) computational cost.*

I had written something in response to this, in which I related the increase in RSA key size simarly showed the reduced delta increase you describe, but in the *security level* bits equivalent values. Despite that between RSA-2048 and RSA-4096, there is still roughly a 40-bit delta(security level/strength representation in bits), which while a little less than 2/3 the amount of security strength bits, the numbers represented by such was by far larger than double, time to attack it would likewise afaik also reflect that.

Thus your statement implying it is not even twice as secure seems invalid? If it's anything like attacking password hashes, just adding one more character to the length can drastically increase time to attack the keyspace. From your response, you seem to be focused on that the RSA key size being double, and how that relates to declining improvements in security strength, but it still seems to be more than double the amount of computational work, just not double the amount of bits (big difference).

---

> *In TLS, nowedays, the RSA keypair has absolutely no impact on data encryption. It is exclusively used only for authentication. Therefore no, you don't have any benefit in using a bigger RSA key than the lowest in the chain.*

I had mentioned something here about SMTP servers and that it's not uncommon for it's TLS support to lag behind. I had also noted some differences with how SMTP messages are exchanged regarding the involvement of TLS, but that's not too important.

Main point I remember was citing [OWASP's *legacy*/D cipher list](https://cheatsheetseries.owasp.org/cheatsheets/TLS_Cipher_String_Cheat_Sheet.html#openssl), where DHE/ECDHE isn't always used, GCM is safe IIRC, but I'm not sure if your statement with RSA applies there, nor on the following cipher suites:

```
AES256-SHA256
AES128-SHA256
AES256-SHA
AES128-SHA
```

This is TLS 1.2, which is still quite relevant for SMTP, in some cases even earlier versions of TLS may still be supported(with stricter selection due to more vulnerabilities). Perhaps your quoted statement was only thinking of modern browsers in regards to TLS with web servers? I'd very much appreciate clarification if your statement still holds true on that OWASP D list.

---

> *This way to exchange the symmetric key is obsolete and should be disabled since it does not provides any forward secrecy: if the private key leaks, every previous communication that has been recorded can now be decrypted. Modern key exchanges uses a Diffie-Hellman key exchange with ephemeral parameters (DHE or the ECDHE).*

As the OWASP link mentions regarding the D list, PFS isn't a certainty, depends on the client connecting. Arguably, some encryption / security is beneficial over none or the failure to deliver/receive emails to users:

> OWASP Cipher String 'D' (Legacy, widest compatibility to real old browsers and legacy libraries and other application protocols like SMTP)

> Take care, use this cipher string only if you are forced to support non PFS for real old clients with very old libraries or for other protocols besides HTTPS.

Your quote about the risk is why I was providing the reference and questioning the README statements assumptions. I agree with you that when ideal, PFS only cipher suites is best and when TLS 1.3 can be used exclusively, or TLS 1.2 with only PFS ciphersuites, that is great. When that is not the case however, there is still benefit to a larger key size for the end-entity certificate yes?

---

> *Conclusion: check the date before believing something you see on the internet, the stackexchange thread dates back in 2011. In 9 years things evolved and what was true at that time is mostly false today (at least about this subject).*

I was aware of the date, but as with your own README advice that I'm seeking clarification on, how recent that advice is doesn't necessarily mean it's entirely correct either(I don't mean to offend by saying that). 

I'll question and investigate the information regardless of date and don't often trust a single source as truth alone, which afaik is the right approach, especially with security concerns. The link in question did point out DHE cipher suites weren't affected btw.

---

## TL;DR

In summary, I am of the understanding that:

1. Regarding computation to attack RSA-4096 vs RSA-2048, there is a ~40-bit delta in *security level* bits, thus it is more than twice in security strength yes?
2. End-entity certificates with a larger key size than root or intermediate certificates, while of no benefit to PFS cipher suites(at least regarding DHE and ECDHE due to ephemeral params used in key exchange), still matters security wise for non-PFS cipher suites which may be in use with TLS 1.2 or earlier for non-HTTPS services such as SMTP. It is beneficial in those cases as it raises the difficulty to decrypt recorded encrypted messages. Agreed?

**Comment by polarathene** [comment]
Only just noticed the RSA link regarding 4096-bit key size, it has an odd argument, since the increase of symmetric bits is not too different from the 1024 to 2048 key size (they didn't cite sources for where they got 28-bits from vs the ~40-bits I cited, which is a notable bump). I still feel that statement is misleading regarding it's increase in difficulty to attack.

> *Unfortunately, as X.509 certificates may be used in various contexts, some software may not support this not-so-recent technology. To achieve maximal compatibility while using ECC, you usually have to set-up an hybrid configuration with both an ECDSA and a RSA certificate to fall-back to.*

This statement, I'd also appreciate some backing on if you have it, perhaps an actual software/context where it applies? (Since you have already responded here that modern TLS should always be using PFS to downplay any added benefit of leaf certs using a larger key size)

[A discussion with certbot project](https://github.com/certbot/certbot/issues/2632#issuecomment-549584840) about dual RSA + ECDSA certs shares many old clients where ECDSA is not supported, and a comment not long after that points out a lack of support for SNI which is commonly used with certificates issued today... In which event, that'd be a problem with RSA as well?

Nothing against the warning (I appreciate it), but it is a bit vague on the subject where I've seen similar mentioned elsewhere, and get the impression it may have just been parroted for some time and for many far less likely to encounter as an issue?

**Comment by breard-r** [comment]
> Thus your statement implying it is not even twice as secure seems invalid?


> Regarding computation to attack RSA-4096 vs RSA-2048, there is a ~40
> bit delta in security level bits, thus it is more than twice in
> security strength yes?

Invalid I don't think so, but obviously badly stated. I guess it's
because I refer to a security level that is not defined and is therefore
very subjective. Although each security bits doubles the number of
computations required to "crack the think" and is therefore exponential,
I tend to read it on a linear scale.

The reason for that is simple: doubling the number of computations will
not really doubles the system's security. Using your parallel with
passwords, if a password can be cracked in 2, 4 or 8 days is still the
same order of magnitude and therefore the same security level although
there is several bits of difference. Instead of days talk in month and
you have a noticeable improvement. Talk in years and there you get
something really better.

As stated in [GnuPG
FAQ](https://gnupg.org/faq/gnupg-faq.html#please_use_ecc) (quoting [SP
800-57 Part
1](https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final)):

> The United States’ National Institute of Standards and Technology
> (NIST) states that RSA-2048 gives roughly 112 bits of security and
> RSA-3072 gives roughly 128. There is no formal recommendation on where
> RSA-4096 lies, but the general consensus is that it would come in
> somewhere around 140 bits — 28 bits of improvement over RSA-2048. This
> is an improvement so marginal that it’s really not worth mentioning.

The NIST also indicates that RSA-7680 gives 192 bits of security, so I
wouldn't have high-hopes on RSA-4096 giving the 168 bits you say.

> End-entity certificates with a larger key size than root or
> intermediate certificates, while of no benefit to PFS cipher suites(at
> least regarding DHE and ECDHE due to ephemeral params used in key
> exchange), still matters security wise for non-PFS cipher suites which
> may be in use with TLS 1.2 or earlier for non-HTTPS services such as
> SMTP. It is beneficial in those cases as it raises the difficulty to
> decrypt recorded encrypted messages. Agreed?

Clients without DHE/ECDHE support are old stuff that are very likely to
be plagued with various security issues. Therefore, I find the small
improvement on the sole key exchange ridiculously negligible and really
not worth the effort. All you will do is increase the calculation
overhead due to the significantly bigger key size.

Try this command to see the impact on performances:

```
openssl speed rsa2048 rsa3072 rsa4096 ecdsap256 ecdsap384 ecdsap521
ed25519 ed448
```

The results will vary depending of the machine you run it on, but most
of the time the ratio will be the same.

If you want to reduce the server's workload, look for the best signature
performances. To reduce the client's workload, look for the best
verification performances. Personally, I tend to sacrifice the client's
performances in favor of the server, therefore ECDSA P-256 is the real
deal for me (and I would also consider Ed25519 and Ed448 when available).

> This statement, I'd also appreciate some backing on if you have it,
> perhaps an actual software/context where it applies? (Since you have
> already responded here that modern TLS should always be using PFS to
> downplay any added benefit of leaf certs using a larger key size)

You already guessed it: SMTP. There is many servers with self-signed
certificates, domain mismatch, prehistoric crypto libraries and so on.
My SMTP server is the only reason why I keep an RSA certificate with a
very loose configuration.

For the dual certificates thing, I don't use it myself but I saw several
people who like it:
https://hackernoon.com/rsa-and-ecdsa-hybrid-nginx-setup-with-letsencrypt-certificates-ee422695d7d3
https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/
https://varunpriolkar.com/2016/10/hybrid-ecdsa-and-rsa-certificates-with-nginx-and-lets-encrypt/

**Comment by polarathene** [comment]
> The reason for that is simple: doubling the number of computations will not really doubles the system's security. 

> Using your parallel with passwords, if a password can be cracked in 2, 4 or 8 days is still the same order of magnitude and therefore the same security level although there is several bits of difference. 

> Instead of days talk in month and you have a noticeable improvement. Talk in years and there you get something really better.

Password strength is often referred to as [bits of entropy](https://en.wikipedia.org/wiki/Password_strength#Entropy_as_a_measure_of_password_strength). If you visit that wikipedia link, you'll find a useful table further down and another section on required entropy. You can go from a few years to over a hundred within 2-3 additional characters. So your noticeable improvement isn't difficult to achieve from increasing the key length, even if it's just adding a few more entropy bits.

I am not familiar with the computation resources to crack RSA-2048, but I would imagine it's still a long way from days, so those marginal bits that exponentially increase the difficulty isn't a meager amount, it's definitely not less than twice.

---

> The NIST also indicates that RSA-7680 gives 192 bits of security, so I wouldn't have high-hopes on RSA-4096 giving the 168 bits you say.

I take it you did not even review the related StackExchange link I provided? (that's ok, I understand you're busy and have more important things to do with your time)

If you visit the link, the actual formula (from the NIST document, page 92) is used to calculate the provided values (which elsewhere you may see are mentioned as approximations), the user provides the code to perform it, but this is the result:

```
$ for x in 1024 2048 3072 4096 7680
do echo $x | ./RSA-NIST.bc ; done
Strength: 79.99990535892915
Strength: 110.11760837749330
Strength: 131.97008244495367
Strength: 149.73076030162618
Strength: 196.25255668821560
```

As you can see the reported values you'll see elsewhere have been rounded to a number divisible by 8 instead (80, 112, 128, 152, 192). For 4096, 149.73 bits rounds up to 152-bit, regardless there is a rough ~40 bit delta against RSA-2048.

For some reason you're citing 128-bits which is RSA-3072. The difference between RSA-1024 and RSA-2048 is only 30-bits. That's roughly a 37% increase in bits, while RSA-2048 vs RSA-4096 is not too different at ~36% increase in bits. 

Do you have any other sources making such justifications that the security level of RSA-2048 vs RSA-4096 is paltry in comparison to the gains from RSA-1024 vs RSA-2048? Because unless I'm missing something here, these are roughly equivalent improvements (slightly diminished none the less). 

The main drawback is actual performance degradation. Security level remains a solid improvement.

---

> Clients without DHE/ECDHE support are old stuff that are very likely to be plagued with various security issues.

All the more reason to not encourage sticking to upstream certificate key sizes by claiming there is no security benefit. There is no harm in the added clarification that the lack of benefit only applies to cipher suites that provide PFS. 

If for whatever reason there is a need to support such clients, the admin should know this already in all fairness, but if you're going to make such a statement I think it would be appreciated that you narrow it down from a blanket statement. You are after all, adding this information to your README to help inform/educate those less knowledgeable on the topic, so lets not mislead them?

> Try this command to see the impact on performances:

> ```
> openssl speed rsa2048 rsa3072 rsa4096 ecdsap256 ecdsap384 ecdsap521
> ed25519 ed448
> ```

|                                           | sign            | verify          | sign/s    | verify/s   |
|------------------------------------|----------------|-----------------|------------|-------------|
| rsa 2048 bits                      | 0.000619s |  0.000019s | 1614.6   | 53725.7 |
| rsa 3072 bits                      | 0.001865s | 0.000038s  | 536.2     | 26465.5 |
| rsa 4096 bits                      | 0.004187s | 0.000065s  | 238.8     | 15322.7 |
| 256 bits ecdsa (nistp256)  | 0.0000s     | 0.0001s      | 40769.7 | 13987.6 |
| 384 bits ecdsa (nistp384)  | 0.0010s     | 0.0008s      | 1005.4   | 1240.7   |
| 521 bits ecdsa (nistp521)  | 0.0003s     | 0.0006s      | 3135.3   | 1577.9   |

Yes, performance is not great, I haven't debated that though. Unless running a large SMTP service where you are receiving from a wide assortment of untrusted third-parties, you're not likely to be receiving at such a frequency that those overheads are going to be a notable concern. 

I would imagine for many, they're either running a small SMTP service or it's an internal/organizational one such as at an enterprise and you have better control / influence over the parties involved, and at the very least should know their requirements already, some legacy software with Java IIRC, cannot use RSA with keys larger than 2048-bits.

Are you monitoring any stats at all for your SMTP service connections? There's [this July 2019 report](https://www.virusfree.cz/en/blog/?id=3VWmpptdQea8D1ZvA4JZqh) that provides some nice insights breaking down TLS protocols used. Less than 3% was TLS 1.0-1.1, 90% TLS 1.2, ~7% TLS 1.3.

I linked to a related issue elsewhere earlier, https://github.com/igrigorik/istlsfastyet.com/issues/208 . This points out that TLS 1.0 from 1999 and TLS 1.1 released in 2006 both received ECDSA support from 2006. If you're even allowing TLS 1.0 to be negotiated (I assume you blacklist any versions of SSL), these clients are effectively >=15 years old, likely with numerous security issues, >=20 for those with TLS 1.0 that include ECDSA support. 

As you can't ensure a secure connection between the two MTAs when other hops can be involved as it's not like HTTPS, and all a server needs to do is decline support for StartTLS over port 25, are you sure that RSA is providing any tangible benefit here with those clients?

It's a different story security wise when the focus is redirected on users retrieving/sending mail via your SMTP service, those are usually performed over ports where a higher level of security has benefit and you have more responsibility towards the users of that service (assuming their clients aren't misbehaving and leaking credentials), ideally they're using secured implicit TLS ports only to connect (something you could enforce, unlike with port 25). But in this scenario, it's less likely for such dated clients to be connecting, we're talking Windows XP here which is well into EOL(last I used that at an enterprise was 2013), EOL is more likely to be respected, and software probably is from a release in at least the past decade. 

Are you using RSA because you know legitimate clients don't support ECDSA, or as a "better safe than sorry" approach because you had seen advice to use dual certs repeated over the years (probably by people who did the same thing).

My point of all that is, not just with SMTP, but the unfortunate cases where it is required (and I've seen requests for dual-certs to support legacy software in enterprises being made still in 2020 for things like k8s nginx ingress controller), the majority of users aren't likely to be using the certificates in a scenario where this matters, and in the majority of cases that it would matter, they'd more than likely be informed well enough to know that they need RSA or dual-cert support(which is interestingly enough not that well supported by newer, but well adopted services such as kubernetes or caddy afaik).

It's better just to raise awareness about it, and link to a resource for those that don't know better such as the [GlobalSign ECDSA compatibility page](https://support.globalsign.com/ssl/ssl-certificates-life-cycle/ecc-compatibility) I had mentioned to you earlier. Generally TLS 1.2 as a minimum and ECDSA certs are going to be a good default choice, not always the best choice but the most common and appropriate, that's what makes for a good default, so long as the user is aware of niche cases regarding compatibility (a valid concern at enterprise level).

---

> For the dual certificates thing, I don't use it myself but I saw several people who like it

The relevance of that usage declines with age (not unlike your dismissal of a StackExchange thread I linked you to initially that's around a decade old), as useful as the information is. 

The HackerNoon article being most recent at 2018, also cites the same GlobalSign compatibility page. But makes the same claim as you have regarding leaf certificate key size for RSA, which is a bit contradicting considering the articles intentions to serve RSA for very old clients, TLS 1.2 as I pointed out here has cipher suites that do not provide PFS, that only becomes more common in earlier versions, which this dual-cert is catering to the needs of, so having a cipher suite setup like OWASP D(legacy) or [Mozilla old](https://wiki.mozilla.org/Security/Server_Side_TLS) is not going to be uncommon?

Personally, as I'm sure you can agree, the dual-cert solution mostly to cater to smoothing the transition. It doesn't help that there is still enterprises that avoid fixing the issue with legacy client usage due to cost/time by still requesting workarounds in 2020, similar to the problem long certificate lifespans was slowing/delaying progress especially in browsers (to the extent Apple ignored protocol with CA/B and enforced 1 year public leaf certificate lifetimes from Sep 2020 onwards, instead of hoping for the CAs to vote in favor of it).

You can do your part when providing advice from your project README to uninformed users, by being less vague in the statements that lead to parroting and "better safe than sorry" reactions (as I am doubtful most look into it further like I have). They may trust your advice without question due to your domain knowledge authoring this project, and then spread that or write articles about it, without knowing better.

---

# TL;DR

- RSA-2048 vs RSA-4096 is still a notable security level boost. It's akin to the same gains as RSA-1024 vs RSA-2048 provides in that regard. Performance does suffer and in general RSA-2048 should still be sufficient or the user is better to switch to ECC, I don't disagree with any of that, just that you are definitely getting more than twice the difficulty to attack it.
- RSA-4096 is 152-bits, it's still a ~40-bit delta to the 112-bit entropy of RSA-2048. RSA-1024 is 80-bit, a delta of 32-bits to RSA-2048. These deltas are roughly the same increase(~37%) in security level (bits of entropy).
- OWASP and Mozilla both provide cipher suites for legacy software usage which contain non-PFS cipher suites for compatibility reasons. These are cases where RSA key size in a leaf certificate does matter, and with the age / vulnerabilities of such legacy systems, security should not be downplayed with blanket statements that are misleading.
- In such scenarios (software >=15 years), even RSA can present problems with key sizes above 2048-bit. It's also quite possible to run into problems with SNI support(many clients did not support this until 2010-2014) and that's a fairly common usage(serving certificates for different services from the same IP). Dual/Hybrid cert support is fine when appropriate, being less vague on the likelihood of such clients is worthwhile.

I provided a PR that better directs the reader to resources that will help them decide appropriate key size or if ECDSA really needs a RSA fallback for them to adopt. It improves what is already very nice information, while retracting or rephrasing some statements that I believe are somewhat misleading. I hope you'll consider it.

I don't think I have anything else to add to this discussion, I've provided adequate information and resources. I really do appreciate your responses, they have been helpful, and I hope mine have been somewhat to you as well. If the above does not convince you to make the changes, I'll just respect that decision and cease debating it.

Thanks for taking the time and patience to discuss this so thoroughly.

**Comment by breard-r** [comment]
>   * RSA-2048 vs RSA-4096 is still a notable security level boost. It's
>     akin to the same gains as RSA-1024 vs RSA-2048 provides in that
>     regard. Performance does suffer and in general RSA-2048 should still
>     be sufficient or the user is better to switch to ECC, I don't
>     disagree with any of that, just that you are definitely getting more
>     than twice the difficulty to attack it.
>   * RSA-4096 is 152-bits, it's still a ~40-bit delta to the 112-bit
>     entropy of RSA-2048. RSA-1024 is 80-bit, a delta of 32-bits to
>     RSA-2048. These deltas are roughly the same increase(~37%) in
>     security level (bits of entropy).

Ok, maybe RSA-4096 bring more security over RSA-2048 than I imagined and
obviously, as I already said, my saying about RSA-4096 not being twice
more secure than RSA-2048 is poorly stated. Yet I'm still not impressed
by RSA-4096.

Anyway, yes, I will rephrase the answer in the FAQ. But maybe not with
the content you provided in the PR.

>   * OWASP and Mozilla both provide cipher suites for legacy software
>     usage which contain non-PFS cipher suites for compatibility reasons.
>     These are cases where RSA key size in a leaf certificate does
>     matter, and with the age / vulnerabilities of such legacy systems,
>     security should not be downplayed with blanket statements that are
>     misleading.

And I advocate not to support those legacy clients. These cipher suites
using RSA as a key exchange should be disabled. This is in accordance to
recommendations R6 and R7 from the security recommendations for TLS [1]
published by the ANSSI (note that the english version is now obsolete,
but those two rules do not differ from the new recommendations that has
been published only in french).

And as I already stated, the very little improvement in security given
to these legacy client is not interesting at all. It's like putting a
band-aid on an open fracture.

[1] https://www.ssi.gouv.fr/en/guide/security-recommendations-for-tls/


>   * In such scenarios (software >=15 years), even RSA can present
>     problems with key sizes above 2048-bit. It's also quite possible to
>     run into problems with SNI support(many clients did not support this
>     until 2010-2014) and that's a fairly common usage(serving
>     certificates for different services from the same IP). Dual/Hybrid
>     cert support is fine when appropriate, being less vague on the
>     likelihood of such clients is worthwhile.

I have no idea what you want to achieve here.

**Comment by polarathene** [comment]
> Yet I'm still not impressed by RSA-4096.

That's fine, my only issue was the misleading statement. I wouldn't advise RSA-4096 either.

> Anyway, yes, I will rephrase the answer in the FAQ. But maybe not with the content you provided in the PR.

Cheers.

> These cipher suites using RSA as a key exchange should be disabled.

The larger point I was making was that in many cases, including SMTP, unless that's your core product, the amount of legitimate clients connecting without support for ECDSA is likely 0 or close to. Any others are probably spam and will send through plaintext anyway. In an enterprise environment, you'd know if you need RSA, and it'd be more of an opt-in via dual-cert or change from default which should probably be ECDSA in most cases.

I would be interested to know of legacy clients that need to disable non-PFS RSA, but don't support ECDSA.

> I have no idea what you want to achieve here.

As the PR shows, clearly reference clients that don't support ECDSA via the GlobalSign link. 

Dual/Hybrid certificate support should rarely be necessary for most creating a certificate these days, they can default to ECDSA. 

These very old clients that are unable to use ECDSA are likely to break in a variety of other ways anyhow.
