### ISSUE TITLE
Allow for not using any pidfile

### ISSUE THREAD

**Issue by ptrcnull** [breard-r/acmed#60]
It's pointless to require a pidfile with any modern process supervisor, or when just running acmed locally in a terminal for debug purposes, especially that it just serves as a lockfile with extra steps.

**Comment by nekopsykose** [comment]
even when not supervising (i.e. default openrc service manager that just starts something and forgets about it), the service manager is supposed to background and manage pidfiles itself, as letting processes create/write pidfiles with their own permissions is useless for the service manager, as that means it will later trust the process to not have written something like `1` into the pidfile and accidentally kill pid 1. not exactly sure when the --pid-file is ever useful here, as it's not really the 'ideal' way for any form of service management.

**Comment by breard-r** [comment]
Indeed. Thanx for the request, I'll add it today.
