### ISSUE TITLE
Include config directories

### ISSUE THREAD

**Issue by lukaslihotzki** [breard-r/acmed#73]
Listing all files in include can be cumbersome. It would be more easy if `include` supported directories or globs instead of single files.

**Comment by breard-r** [comment]
As stated in [the man page](https://github.com/breard-r/acmed/blob/v0.21.0/man/en/acmed.toml.5#L365-L377), the `include` directive already supports Unix style globing. This is implemented using the [glob](https://crates.io/crates/glob) crate.

For example, you can write the following:
``` toml
include = [                                                                                                                                                                                                                                                                                                                
    "endpoints.toml",
    "some_directory/*.toml"
]
```
